<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Speaker;
use Carbon\Carbon;  

class SpeakerSeeder extends Seeder
{
    public function run(): void
    {
        $speakers = [
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Federico De Arteaga Vidiella',
                'profession'   => 'Ph.D. en Innovación y Responsabilidad Social',
                'bio'          => 'Experto con Doctorado (Ph.D.) en Innovación y Responsabilidad Social, MBA en Negocios Internacionales e Ingeniería Agrónoma. Su trayectoria profesional se destaca por su liderazgo como Presidente de la Red de Destinos Turísticos Inteligentes de Iberoamérica y su rol como consultor de alto nivel para el Banco Interamericano de Desarrollo (BID) en proyectos de gobernanza y sostenibilidad. Posee una vasta experiencia en la implementación de metodologías de turismo inteligente, habiendo asesorado a entidades como la SECTUR en México y la Secretaría de Turismo de Cali en Colombia. Su experiencia se complementa con una sólida visión corporativa, forjada como director en Grupo JB (Mundo Cuervo). Fue seleccionado por su perfil único que integra una rigurosa formación académica con experiencia probada en la creación y gobernanza de modelos sostenibles e innovadores en el sector público y privado a escala internacional.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Javier Suescún',
                'profession'   => 'Magíster en Educación',
                'bio'          => 'Comunicador Social egresado de la Universidad de Pamplona y candidato a Magíster en Educación. Cuenta con una sólida trayectoria en producción audiovisual y fotografía, desempeñándose en diversos medios y productoras. Tiene más de 10 años de experiencia como docente universitario en fotografía, televisión y medios audiovisuales.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'María Cecilia López',
                'profession'   => 'Magister en Mercadeo, Diseñadora de Modas',
                'bio'          => 'Magister en mercadeo y Profesional en Diseño de Modas y textiles con más de 27 años de experiencia. Conferencista Nacional e Internacional y co-autora de libros sobre diseño de modas y cultura.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Andrés Díaz Molina',
                'profession'   => 'Ingeniero de Sistemas, Especialista en Seguridad de la Información y Derecho Informático',
                'bio'          => 'Ingeniero de Sistemas, especialista en Seguridad de la Información y Derecho Informático. Ha liderado estrategias de ciberseguridad en entidades públicas como MinTIC y ICBF. Cuenta con más de 16 años de experiencia en el sector público.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Jhon Faber Giraldo',
                'profession'   => 'Comunicador Social y Estratega de Contenido',
                'bio'          => 'Comunicador social y apasionado por el marketing, turismo, cultura y café. Fotógrafo, estratega y creador de contenido audiovisual en el equipo de Marketing del Parque Nacional del Café desde hace 26 años.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Lucas López',
                'profession'   => 'Magíster en Diseño y Creación Interactiva',
                'bio'          => 'Diseñador de la Comunicación Gráfica y Magíster en Diseño y Creación Interactiva. Ha trabajado como docente de cátedra y es autor de la publicación "Ciudades legibles".',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Alberto Mena',
                'profession'   => 'Consultor Estratégico, CEO de X-TRATEGIC',
                'bio'          => 'Consultor estratégico, CEO y fundador de X-TRATEGIC, firma líder en El Salvador especializada en asesoría para el sector hotelero y turístico. Cuenta con más de 12 años de experiencia en turismo.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Juan Carlos León',
                'profession'   => 'Maestrante en Gestión de las Organizaciones',
                'bio'          => 'Maestrante en Gestión de las Organizaciones, profesional en diseño de modas y alta costura, con estudios en diseño textil y producción industrial de confecciones.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Natalia Bayona',
                'profession'   => 'Pionera en Promoción Turística',
                'bio'          => 'Pionera en la administración pública y promoción turística. Trabajó para ProColombia y fue la gestora más joven de promoción turística de Colombia en 2013.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Wilfer Montoya Benjumea',
                'profession'   => 'Diseñador Visual y Compositor VFX',
                'bio'          => 'Diseñador visual y compositor VFX para cine y televisión con más de 11 años de experiencia. Explora la inteligencia artificial generativa para la producción audiovisual.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Otniel Josafat López Altamirano',
                'profession'   => 'Doctor en Diseño de Producto',
                'bio'          => 'Doctor en Diseño de Producto (UNESP, Brasil) y Maestría en Diseño Digital. Investigador reconocido por el SNI de México y profesor titular en la UABJO.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Ricardo Alexis López Gallego',
                'profession'   => 'Consultor en Finanzas para la Conservación',
                'bio'          => 'Consultor en Finanzas para la Conservación con más de 12 años de experiencia en estrategias de financiamiento para proyectos ambientales y cambio climático.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Gerardo Luna Gijón',
                'profession'   => 'Especialista en Diseño de Información',
                'bio'          => 'Profesor de tiempo completo en la BUAP, especializado en diseño de información, diseño editorial y UX. Su trabajo se centra en la intersección entre diseño y divulgación científica.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Miguelina Ruiz Díaz',
                'profession'   => 'Especialista en Marketing Turístico',
                'bio'          => 'Licenciada en Administración Hotelera y especialista en Marketing Turístico. Ha trabajado en promoción turística en Venezuela y actualmente es directora de la OPT en Colombia.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Héctor Daniel Martínez',
                'profession'   => 'Experto Internacional en Turismo Rural',
                'bio'          => 'Licenciado en Turismo y Experto Internacional en Turismo Rural y Desarrollo Turístico Sustentable. Amplia experiencia en planificación estratégica y proyectos turísticos.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Alejandra Izquierdo Cujar',
                'profession'   => 'Líder Étnica y Asesora en Asuntos Legislativos',
                'bio'          => 'Líder étnica del pueblo IKU y asesora en asuntos legislativos en la Cámara de Representantes. Ingeniera Industrial con maestría en Project Management y Gestión Pública.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Andrea Paola Santanilla Narvaez',
                'profession'   => 'Economista y Maestría en Economía',
                'bio'          => 'Economista con maestrías en economía y emprendimiento social. Lidera la Dirección de Inversión Extranjera y Servicios en Mincomercio.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Luis Aníbal Mora García',
                'profession'   => 'Ingeniero Industrial y Especialista en Logística',
                'bio'          => 'Ingeniero Industrial de la Universidad Nacional de Colombia, especialista en Mercadeo Internacional y Maestría en Dirección Logística. Docente catedrático en múltiples universidades.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Angela Pantoja',
                'profession'   => 'Especialista en Turismo Comunitario y Sostenible',
                'bio'          => 'Profesional con más de 11 años de experiencia en diseño e implementación de estrategias turísticas innovadoras y sostenibles. Lideró la estrategia de marca de turismo comunitario de Bogotá.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Franklin Eduardo López',
                'profession'   => 'Magíster en Dirección de Marketing Estratégico',
                'bio'          => 'Publicista y Magíster en Dirección de Marketing Estratégico. Docente investigador en publicidad y marketing digital en la Universidad de Investigación y Desarrollo (UDI).',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Julio César Acosta Prado',
                'profession'   => 'Doctor en Dirección y Organización de Empresas',
                'bio'          => 'Post-Doctor en Administración y Doctor en Dirección y Organización de Empresas. Profesor visitante y consultor internacional con experiencia en gestión del conocimiento e innovación.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Manuel Fernández-Villacañas Marín',
                'profession'   => null,
                'bio'          => 'Sin información disponible actualmente.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Lucía Corali Nelly Risco Mc Gregor',
                'profession'   => 'Magíster en Administración y Negocios Internacionales',
                'bio'          => 'Magíster en Administración y Negocios Internacionales, Diseñadora de Interiores y docente en la Universidad Peruana de Ciencias Aplicadas.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Karina Vélez Gómez',
                'profession'   => 'Especialista en Comunicaciones y Medios',
                'bio'          => 'Experiencia de 15 años en telecomunicaciones, liderando estrategias de posicionamiento para Telefónica en Hispanoamérica.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Magreth Gutiérrez Vargas',
                'profession'   => 'Ingeniera Financiera',
                'bio'          => 'Ingeniera financiera, CEO y fundadora de Aavance Solutions Fintech SAS. Premiada como una de las mujeres más influyentes en proyectos innovadores.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Asia Pellegrini',
                'profession'   => 'Licenciada en Business Management',
                'bio'          => 'Co-fundadora de Nothink Shoes, marca europea de calzado con tacones intercambiables. Licenciada in Business Management.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Luna T. García',
                'profession'   => 'Técnica en Administración y Finanzas',
                'bio'          => 'Co-fundadora de Nothink Shoes, especialista en expansión de marcas hispanohablantes.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Juan Carlos Peña Castro',
                'profession'   => 'MBA en Business & Marketing',
                'bio'          => 'Profesional en Finanzas y Relaciones Internacionales, MBA in Business & Marketing. Especialista en transformación digital y customer-centric strategies.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Alejandro Fajardo',
                'profession'   => 'Especialista en Gestión de Proyectos Turísticos',
                'bio'          => 'Ingeniero agrónomo y especialista en gestión de proyectos turísticos. Experiencia en turismo comunitario, etnoturismo y planificación territorial.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Angela María Galindo Cañon',
                'profession'   => 'Maestra en Textiles y Máster en Alta Dirección',
                'bio'          => 'Maestra en Textiles y Máster en Alta Dirección. Profesional en Gestión en Artesanías de Colombia, coordinando programas de innovación textil y fortalecimiento empresarial.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Claudia Marcela Sanz',
                'profession'   => 'Doctora en Diseño',
                'bio'          => 'Doctora en diseño, Directora del Programa de Diseño de Vestuario de la Universidad de San Buenaventura. Investigadora y autora de libros sobre diseño y moda.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Carlos Enrique Fernández García',
                'profession'   => 'Magíster en Educación',
                'bio'          => 'Magíster en Educación y Comunicador experto en tecnologías emergentes y realidad aumentada aplicadas al periodismo y diseño profesional.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Amalia Aguilar Castillo',
                'profession'   => 'Doctorado en Educación',
                'bio'          => 'Economista y actualmente cursando el Doctorado en Educación. Directora de la Facultad de Comercio Internacional y Aduanas de la Universidad Xochicalco.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'uuid'         => Str::uuid(),
                'name'         => 'Diego Santos González',
                'profession'   => 'Doctor en Sociología del Turismo',
                'bio'          => 'Doctor en Sociología del Turismo por la Universidad Rey Juan Carlos. Director de programas de máster en Turismo de EAE Business School.',
                'photo'        => null,
                'website'      => null,
                'social_links' => null,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
        ];

        foreach ($speakers as $speaker) {
            Speaker::create($speaker);
        }

        $this->command->info('Ponentes creados exitosamente!');
    }
}